TestCase/GraphWeb/Models/GraphCalculationResultViewModel.cs
using GraphWeb.GraphReader;
using GraphWeb.GraphService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GraphWeb.Models
{
	/// <summary>
	/// Class representing calculation result for result page.
	/// </summary>
	public class GraphCalculationResultViewModel
	{
		/// <summary>
		/// Result to display
		/// </summary>
		public CalculateContract CalculateContract { get; private set; }

		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="calculateContract">Result to display</param>
		public GraphCalculationResultViewModel(CalculateContract calculateContract)
		{
			if (calculateContract == null)
				throw new ArgumentNullException("calculateContract");

			CalculateContract = calculateContract;
		}
	}
}

TestCase/GraphWeb/Controllers/GraphController.cs
using GraphWeb.GraphService;
using GraphWeb.GraphReader;
using GraphWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GraphWeb.Controllers
{
	/// <summary>
	/// Class representing graph controller. Handles user requests for view graph and calculate shortest path in graph.
	/// </summary>
	public class GraphController : Controller
	{
		/// <summary>
		/// Service for calculating shortest path in graph
		/// </summary>
		protected IGraphService _graphService;

		/// <summary>
		/// Service for getting graph structure
		/// </summary>
		protected IGraphReader _graphReader;

		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="graphService">Calculation service</param>
		/// <param name="graphReader">Graph structure retrieving service</param>
		public GraphController(IGraphService graphService, IGraphReader graphReader)
		{
			if (graphService == null)
				throw new ArgumentNullException("graphService");

			if (graphReader == null)
				throw new ArgumentNullException("graphReader");

			_graphService = graphService;
			_graphReader = graphReader;
		}

		/// <summary>
		/// Index action displays graph structure.
		/// </summary>
		/// <returns>View with graph structure</returns>
		[HttpGet]
		public ActionResult Index()
		{
			var graph = _graphReader.GetGraph();

			return View(graph);
		}

		/// <summary>
		/// Calculates shortest path between specified nodes.
		/// </summary>
		/// <param name="idFirst">Id of first node</param>
		/// <param name="idSecond">Id of second node</param>
		/// <returns>View with graph calculation result</returns>
		[HttpPost]
		public ActionResult CalculateShortestPath(int idFirst, int idSecond)
		{
			var first = _graphReader.GetNode(idFirst);
			var second = _graphReader.GetNode(idSecond);

			if (first == null || second == null || idFirst == idSecond)
				return PartialView("Message", "Select two different nodes.");

			var contract = _graphService.CalculatePath(idFirst, idSecond);

			if(contract == null)
				return PartialView("Message", "Path not found.");

			return PartialView(new GraphCalculationResultViewModel(contract));
		}
	}
}

TestCase/GraphWeb/Views/Graph/CalculateShortestPath.cshtml
@model GraphWeb.Models.GraphCalculationResultViewModel

<div>
	From: @Model.CalculateContract.From.Label<br />
	To: @Model.CalculateContract.To.Label<br />

	@if (Model.CalculateContract.Path.Length > 0)
	{
		<p>Nodes to visit: 
		@foreach (var node in Model.CalculateContract.Path)
		{
			@:[ @node.Label ]
		}
		</p>
	}
	else
	{
		<p>Path not found</p>
	}
</div>

TestCase/GraphWeb/Views/Graph/Index.cshtml
@model GraphWeb.GraphReader.GraphContract

@{
    Layout = "~/Views/_Layout.cshtml";
}

<style type="text/css">
	#graph {
		width: 600px;
		height: 400px;
		border: 1px solid lightgray;
		font-size: 20px;
	}
</style>

<div id="graph"></div>

@if (Model != null)
{
	<script type="text/javascript">
		var nodes = new vis.DataSet([
		@if (Model.Nodes != null)
		{
			foreach (var node in Model.Nodes)
			{
				@:{ id: @node.Id, label: '@node.Label' },
			}
		}
		]);
	
		var edges = new vis.DataSet([
		@if (Model.Edges != null)
		{
			foreach (var edge in Model.Edges)
			{
				@:{ from: @edge.IdFirst, to: @edge.IdSecond },

			}
		}
		]);

		var container = document.getElementById('graph');
		var data = {
			nodes: nodes,
			edges: edges
		};
		var options = {
			"edges": {
				selectionWidth: 0
			},
			"physics": {
				"enabled": false
			}
		};
		var network = new vis.Network(container, data, options);
		network.on("click", function (params) {
			SelectNode(params.nodes[0])
		});

		var firstSelected = 0;
		var lastSelected = 0;

		function SelectNode(id)
		{
			if(firstSelected == 0)
			{
				firstSelected = id;
				lastSelected = id;
			}

			firstSelected = lastSelected;
			lastSelected = id;

			document.getElementById('hidden_id_first').value = firstSelected;
			document.getElementById('hidden_id_second').value = lastSelected;

			network.setSelection({
				nodes: [firstSelected, lastSelected],
				edges: [],
				unselectAll: true,
				highlightEdges: false
			});
		}

	</script>

	using(Ajax.BeginForm("CalculateShortestPath", "Graph", new AjaxOptions{
		HttpMethod = "POST",
		InsertionMode = InsertionMode.Replace,
		UpdateTargetId = "calculate_result"
	}))
	{
		<input type="hidden" id="hidden_id_first" name="idFirst" value="0" />
		<input type="hidden" id="hidden_id_second" name="idSecond" value="0" />
		<button type="submit">Calculate shortest path</button>
	}

	<div id="calculate_result"></div>
}

TestCase/GraphWeb/Views/Graph/Message.cshtml
@model string

<div>
	@Model
</div>

TestCase/GraphWeb/Views/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Graph Web</title>
	@Scripts.Render("~/js/vis")
	@Styles.Render("~/css/vis")
</head>
<body>
    <div>
        @RenderBody()

		@Scripts.Render("~/js/jquery")
    </div>
</body>
</html>